//
// Z:\workspace\sprites\plasmablue5\plasmablue5
//

$spritename    plasmablue5
$type          vp_parallel
$texture		alphatest
$load		plasmablue5001.BMP
$frame		0   0   128   128
$load		plasmablue5002.BMP
$frame		0   0   128   128
$load		plasmablue5003.BMP
$frame		0   0   128   128
$load		plasmablue5004.BMP
$frame		0   0   128   128
$load		plasmablue5005.BMP
$frame		0   0   128   128
$load		plasmablue5006.BMP
$frame		0   0   128   128
$load		plasmablue5007.BMP
$frame		0   0   128   128
$load		plasmablue5008.BMP
$frame		0   0   128   128
$load		plasmablue5009.BMP
$frame		0   0   128   128


