//
// C:\Users\Surreal\Desktop\sp\B-Tele1
//

$spritename    B-Tele1
$type          vp_parallel
$texture		additive
$load		B-Tele1001.BMP
$frame		0   0   80   80
$load		B-Tele1002.BMP
$frame		0   0   80   80
$load		B-Tele1003.BMP
$frame		0   0   80   80
$load		B-Tele1004.BMP
$frame		0   0   80   80
$load		B-Tele1005.BMP
$frame		0   0   80   80
$load		B-Tele1006.BMP
$frame		0   0   80   80
$load		B-Tele1007.BMP
$frame		0   0   80   80
$load		B-Tele1008.BMP
$frame		0   0   80   80
$load		B-Tele1009.BMP
$frame		0   0   80   80
$load		B-Tele1010.BMP
$frame		0   0   80   80
$load		B-Tele1011.BMP
$frame		0   0   80   80
$load		B-Tele1012.BMP
$frame		0   0   80   80
$load		B-Tele1013.BMP
$frame		0   0   80   80
$load		B-Tele1014.BMP
$frame		0   0   80   80
$load		B-Tele1015.BMP
$frame		0   0   80   80
$load		B-Tele1016.BMP
$frame		0   0   80   80
$load		B-Tele1017.BMP
$frame		0   0   80   80
$load		B-Tele1018.BMP
$frame		0   0   80   80
$load		B-Tele1019.BMP
$frame		0   0   80   80
$load		B-Tele1020.BMP
$frame		0   0   80   80
$load		B-Tele1021.BMP
$frame		0   0   80   80
$load		B-Tele1022.BMP
$frame		0   0   80   80
$load		B-Tele1023.BMP
$frame		0   0   80   80
$load		B-Tele1024.BMP
$frame		0   0   80   80
$load		B-Tele1025.BMP
$frame		0   0   80   80


