//
// Z:\sprites\animglow01\animglow01
//

$spritename    animglow01
$type          vp_parallel
$texture		additive
$load		animglow01001.BMP
$frame		0   0   64   64
$load		animglow01002.BMP
$frame		0   0   64   64
$load		animglow01003.BMP
$frame		0   0   64   64
$load		animglow01004.BMP
$frame		0   0   64   64
$load		animglow01005.BMP
$frame		0   0   64   64
$load		animglow01006.BMP
$frame		0   0   64   64
$load		animglow01007.BMP
$frame		0   0   64   64


