FROM ice-ubuntu-base
LABEL maintainer="solidi"
LABEL version="0.1"
LABEL description="Builds the ice.so/client.so lib for Cold Ice Goldsrc."

COPY . /usr/local/

WORKDIR "/usr/local/linux"
RUN make clean
RUN make hl
RUN make hl_cdll
