FROM ice-ubuntu-base
LABEL maintainer="solidi"
LABEL version="0.1"
LABEL description="Builds the gravebot.so lib for Cold Ice Goldsrc."

COPY . /usr/local/grave-bot

WORKDIR "/usr/local/grave-bot/dlls"
RUN make clean
RUN make
